[airlock]
plan_path = "components/airlock"

[builder-admin-proxy]
plan_path = "components/builder-admin-proxy"

[builder-admin]
plan_path = "components/builder-admin/habitat"
paths = [
  "components/builder-admin/*",
  "components/builder-http-gateway/*",
  "components/builder-protocol/*",
  "components/core/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]

[builder-api-proxy]
plan_path = "components/builder-api-proxy/habitat"
paths = [
  "components/builder-web/*",
]

[builder-api]
plan_path = "components/builder-api/habitat"
paths = [
  "components/builder-api/*",
  "components/builder-core/*",
  "components/builder-depot/*",
  "components/github-api-client/*",
  "components/segment-api-client/*",
  "components/oauth-client/*",
  "components/builder-http-gateway/*",
  "components/builder-protocol/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]

[builder-datastore]
plan_path = "components/builder-datastore"

[builder-jobsrv]
plan_path = "components/builder-jobsrv/habitat"
paths = [
  "components/builder-jobsrv/*",
  "components/builder-core/*",
  "components/builder-protocol/*",
  "components/builder-db/*",
  "components/core/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]

[builder-originsrv]
plan_path = "components/builder-originsrv/habitat"
paths = [
  "components/builder-originsrv/*",
  "components/builder-protocol/*",
  "components/builder-db/*",
  "components/core/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]

[builder-router]
plan_path = "components/builder-router/habitat"
paths = [
  "components/builder-router/*",
  "components/builder-protocol/*",
  "components/core/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]

[builder-worker]
plan_path = "components/builder-worker/habitat"
paths = [
  "components/builder-worker/*",
  "components/builder-core/*",
  "components/builder-protocol/*",
  "components/core/*",
  "components/net/*",
  "support/ci/builder-base-plan.sh",
]
