log_level = "info"
auto_publish = true
bldr_channel = "unstable"
bldr_url = "https://bldr.habitat.sh"
features_enabled = ""
airlock_enabled = true
recreate_ns_dir = false

[github]
api_url = "https://api.github.com"
app_id = 5565
