log_level = "info"
auto_publish = true
bldr_channel = "unstable"
bldr_url = "https://bldr.habitat.sh"
features_enabled = ""
airlock_enabled = false
recreate_ns_dir = false
target = "x86_64-linux"
work_poll_interval_secs = 60

[github]
api_url = "https://api.github.com"
app_id = 5565
