app_url                 = "https://bldr.habitat.sh"
cookie_domain           = ""
demo_app_url            = "https://www.habitat.sh/demo/build-system/steps/1/"
docs_url                = "https://www.habitat.sh/docs"
enable_publisher_amazon = false
enable_publisher_azure  = false
enable_publisher_docker = false
enable_builder          = false
environment             = "production"
hosted                  = false
source_code_url         = "https://github.com/habitat-sh/habitat"
status_url              = "https://status.habitat.sh/"
tutorials_url           = "https://www.habitat.sh/learn"
use_gravatar            = true
www_url                 = "https://www.habitat.sh"

[analytics]
company_id          = ""
company_name        = ""
enabled             = false
write_key           = ""

[github]
app_id       = 5565
app_url      = "https://github.com/apps/habitat-builder"
api_url      = "https://api.github.com"

[oauth]
authorize_url  = "https://github.com/login/oauth/authorize"
client_id      = ""
provider       = "github"
redirect_url   = ""
signup_url     = "https://github.com/join"

[nginx]
worker_connections   = 8000
worker_processes     = "auto"
worker_rlimit_nofile = 8192
max_body_size        = "1024m"
proxy_send_timeout   = 60
proxy_read_timeout   = 60
limit_req_zone       = "$binary_remote_addr zone=mylimit:10m rate=1r/s"

[http]
keepalive_timeout = "20s"
sendfile          = "on"
tcp_nopush        = "on"
tcp_nodelay       = "on"

[server]
listen_port               = 80
listen_tls_port           = 443
listen_tls                = false
cert_file                 = "ssl-certificate.crt"
cert_key_file             = "ssl-certificate.key"
ssl_protocols             = "TLSv1 TLSv1.1 TLSv1.2"
ssl_ciphers               = "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"
ssl_session_cache         = "shared:SSL:10m"
ssl_session_timeout       = "10m"
ssl_prefer_server_ciphers = "on"
