# Minio must be started with static number of server/disk by design
# It is allowed to extend cluster with new servers in a controlled way
# Run command must be same on all instances

# There are 2 possible ways to run minio:
# --= Standalone mode =--
# Best for local experiments
#
# --= Explicit Cluster =--
#
# Recommended for production environments: explicitly set cluster members.
# From minio server documentation:
# DIR points to a directory on a filesystem. When you want to combine
#   multiple drives into a single large system, pass one directory per
#   filesystem separated by space. You may also use a '...' convention
#   to abbreviate the directory arguments. Remote directories in a
#   distributed setup are encoded as HTTP(s) URIs.
#
# ~members~ is a ~Array~ of DIRs
# When members is empty standalone mode will be used with svc_data_path
members = []

# Default bucket name to create
bucket_name = "habitat-builder-artifact-store.default"

# Bind to a specific ADDRESS (can be an IP or hostname). Default - all
bind_address = ""
# Bind to a specific PORT
bind_port = 9000

# For backward compatibility these values are used if set:
# key_id = "depot"
# secret_key = "password"

# Setup additional environment variables to pass to minio
# Doc: https://docs.min.io/docs/minio-server-configuration-guide.html
[env]
# Set minio admin user and password
MINIO_ACCESS_KEY = "depot"
MINIO_SECRET_KEY = "password"

# Specify private key password for TLS mode
# Note:
#   minio automatically switches to tls if private.key and public.crt files
#   were found in svc_files_path
# MINIO_CERT_PASSWD = "certificate-password"

# MINIO_BROWSER = "off"
# MINIO_DOMAIN = "mydomain.com"
